express/package-lock.json, express/package.json, fastify/package-lock.json, fastify/package.json, hapi17/package-lock.json, hapi17/package.json, hapi18/package-lock.json, hapi18/package.json, koa/package-lock.json, koa/package.json, kraken/package-lock.json, kraken/package.json, loopback/package-lock.json, loopback/package.json, package.json, test-bench-utils/package.json
This changes a couple things:
- Adds `@contrast/test-bench-utils` to the `package-lock.json` file for each app. This keeps versions in check and allows `npm ci` to be used when installing deps for a specific application.
- `lerna bootstrap` runs with the `--ci` option by default. This runs `npm ci` instead of `npm install` when bootstrapping.
- Adds a `npm install --package-lock-only` postversion step for each app/package. This ensures that when we bump versions using `lerna version` updated versions are persisted to the package-lock
=> Investigating `npm ci` with lerna

test-bench-utils/lib/routes.js
Removes input types which can potentially clash in speedracer input analysis.
=> NODE-734 Remove 'body' endpoints from XSS rules

README.md, express/package-lock.json, express/package.json, fastify/package-lock.json, fastify/package.json, hapi17/package-lock.json, hapi17/package.json, hapi18/package-lock.json, hapi18/package.json, hapi19/package-lock.json, hapi19/package.json, koa/package-lock.json, koa/package.json, kraken/package-lock.json, kraken/package.json, lerna.json, loopback/package-lock.json, loopback/package.json, package.json, test-bench-utils/README.md, test-bench-utils/lib/sinks/ssjs.js, test-bench-utils/package-lock.json, test-bench-utils/package.json, test-bench-utils/public/views/xss.ejs
SSJS sinks naively always returned result from the function.  This fails in most because in certain cases attacks return a function.  This just helps avoid noise when debugging screener failures
=> added check to not fail when injecting a function into ssjs sinks

koa/index.js, koa/package-lock.json, koa/package.json
Added the new `@koa/router` and use by default. I just kept the old around for testing via env var `LEGACY_ROUTER`
=> added support for both koa routers

express/package-lock.json, express/package.json, fastify/package-lock.json, fastify/package.json, hapi17/package-lock.json, hapi17/package.json, hapi18/package-lock.json, hapi18/package.json, hapi19/package-lock.json, hapi19/package.json, koa/package-lock.json, koa/package.json, kraken/package-lock.json, kraken/package.json, lerna.json, loopback/package-lock.json, loopback/package.json, test-bench-utils/lib/sinks/nosqlInjection/dynamodb.js, test-bench-utils/package-lock.json, test-bench-utils/package.json
Steps to Verify:
0. `npm i && npm link` in `test-bench-utils/` and `npm link @contrast/test-bench-utils` in whatever test bench app you use.
1. Spin up any test bench app 
2. Hit the routes and confirm `nosql-injection` gets reported
Additional Notes: 
- Once you hit the route you might see the rule report twice. I spent some time trying to dig in to why this was happening but could not discover the root cause. It looks like the post-hook runs twice for some reason
=> Node 873 stub dynamodb sinks

test-bench-utils/lib/sinks/unsafeFileUpload.js
We changed the signatures to sinks to be an object.  However unsafe file upload doesn't use the `utils.getInput`, so the sink was updated to pass in an object with a key of `input` when it didn't have to be
=> fixed the unsafe file upload sink

restify/vulnerabilities/unvalidatedRedirect/index.js, test-bench-utils/lib/sinks/unvalidatedRedirect.js
Restify allows you to pass an object in as first arg to `res.redirect`. This adds that capability
=> added logic to account for another redirect use case

fastify/routes/unsafeFileUpload.js
This was a regression when we refactored the test-bench-utils a few weeks ago.
Steps to reproduce, use this harness to make a request
```
import requests
import os
session = requests.Session()
f = open(os.path.join('./bad-file.php'), mode='rb')
files = { 'file': ('bad-file.php', f.read().decode(errors='replace')) }
req = requests.Request('POST', 'http://localhost:3000/unsafeFileUpload/body/upload', files=files, headers={'Accept': 'text/html'}).prepare()
response = session.send(req, allow_redirects=False, verify=False)
print(response)
```
Expected result 200 with response of `done`.
**Note**: You don't need the agent to repro
=> fixed ufu handler now that it returns an object

restify/utils/controllerFactory.js, restify/utils/wrapHandler.js, restify/vulnerabilities/unsafeFileUpload/index.js
It occurred to me while trying to support protect in restify that it doesn't natively support async handlers.  Similarly to express we need a shim in the handlers to properly wrap them in try/catch.
=> wrap async restify handlers to ensure framework can properly handle errors

express/package-lock.json, express/package.json, test-bench-utils/lib/sinks/xxe.js, test-bench-utils/package-lock.json, test-bench-utils/package.json
- Made Libxmljs as an optional dependency
- Bump sqlite to 5.0.0 in express and test-bench-utils
- Libxmljs workaround for Node 14
=> Make Libxmljs an optional dependency. Bump sqlite3 to 5.0.0

express/entry.sh, fastify/entry.sh, hapi18/entry.sh, hapi19/entry.sh, kraken/entry.sh, loopback/entry.sh, restify/entry.sh
I didn't test all of these.  But I did sanity check with fastify that the agent still started (and had already done so with express).  I also added some timing log statements at the first line in the script and just before executing the agent to check how long that gap was - I ran with the old and new way twice:
```
old way:
pm debug start 1603396062
pm debug starting agent 1603396110
pm debug start 1603396183
pm debug starting agent 1603396228
new way:
pm debug start 1603396347
pm debug start agent 1603396350
pm debug start 1603396413
pm debug start agent 1603396416
```
so 3 seconds vs. ~45 seconds.
=> don't npm install agent

express/vulnerabilities/cspHeaderInsecure/views/index.ejs
Pointing to installed view, not the one in top-level monorepo.
=> NODE-1138: point to @contrast/test-bench-utils in node_modules

loopback4/Dockerfile
I forgot to update this framework-local Dockerfile when removing python/aws deps from images.
Tested running screener against locally-built running container in Node 12 Assess mode:
```
NODE_CONFIG_DIR=./test/screener/config SCREENER_APP_URL=http://localhost:3000 SCREENER_RMQ_PASSWORD=guest SCREENER_RMQ_USERNAME=guest SCREENER_RMQ_HOSTNAME=localhost SCREENER_RMQ_PORT=5672 ./node_modules/.bin/mocha test/screener/apps/loopback4/assess/12.test.js
loopback4:assess:12                                                                                                                                          
[autocomplete-missing/unsafe] GET /autocompleteMissing                                                                                                     
✓ application returns a response …
```
=> remove python/aws install

kraken/index.js, kraken/package-lock.json, kraken/package.json
- Bump kraken-js to 2.3
- Implement new onKrakenMount feature
I'm pretty sure we're good to bump this. Not much has changed in 2.3: https://github.com/krakenjs/kraken-js/compare/v2.0.0...v2.3.0 I used the new onKrakenMount feature to make sure but we don't have to keep it. Tested on new screener with Node 10, 12, and 14 with all passing.
=> NODE 1275: Kraken-js 2.3

.github/workflows/build.yml
Looks like older Docker versions pushed all tagged images by default but now you have to specify the tag unless using --all-tags (-a) option
=> Push all tagged images to ECR

express/index.js, express/package-lock.json, express/package.json, koa/index.js, koa/package-lock.json, koa/package.json
There was some confusion because the ticket specifies: 
> Express-test-bench should be adapted to use the standard library http2
> Koa-test-bench should be adapted to use the spdy library
but according to some of the documentation included in that same ticket: https://www.perimeterx.com/tech-blog/2019/http2/
> We need to have couple of changes if we want to apply HTTP/2 on our Express server. We can’t use the native HTTP/2 library directly, so we will use the spdy library. 
So I'm assuming it was a typo and that Koa should be adapted to use the native HTTP/2 library and Express should use Spdy. It doesn't look like Express will be compatible with the native library any time soon: https://github.com/expressjs/express/issues/3388
=> NODE 1428: Adapt express and koa to use HTTP/2

express/vulnerabilities/unsafeFileUpload/index.js, fastify/routes/unsafeFileUpload.js, koa/routes/unsafeFileUpload.js, kraken/controllers/unsafeFileUpload/index.js, restify/vulnerabilities/unsafeFileUpload/index.js
The errors this change addresses:
```
express:assess:12   
[reflected-xss/unsafe] POST /unsafeFileUpload/body/upload
finding is reported:
AssertionError: finding was not reported for reflected-xss: expected null to be an object
at Context.<anonymous> (test/screener/utils/assertions/assess-finding.js:21:31)
express:monitor:10
[reflected-xss/unsafe] POST /unsafeFileUpload/body/upload              
exploit is reported:
AssertionError: attack did not exploit instead: 3: expected 3 to equal 2
+ expected - actual
-3                                                                                   
+2                            
```
https://github.com/Contrast-Security-OSS/NodeTestBenches/commit/2c3492b299daf79de92888908596ab57d6b5cf0e replaced the "sink" property in SinkData with "sinks: …
=> NODE 1587: Fix screener regression

scripts/Dockerfile, scripts/entry.sh
`entry.sh` is executed in an environment with no network access and installing production-only dependencies was not enough to launch the rewriter.
=> Added an option to use the standalone rewriter with any app

test-bench-utils/lib/frameworks.js
In order to tests the new Sails app, this should be merged and released first, otherwise Sails has no routes.
=> Add Sails to the list of frameworks

test-bench-utils/lib/sinks/nosqlExpansion.js
We need to remove the try-catch blocks in these endpoints as they "catch" the SecurityException we throw when we want to block a request resulting in Status code of 200 with error msg instead of 403.
=> Remove try-catch blocks

test-bench-utils/lib/sinks/nosqlInjection/mongodb.js, test-bench-utils/types/sinks/nosqlInjection/index.d.ts, test-bench-utils/types/sinks/nosqlInjection/mongodb.d.ts
I think there is no need to test the entire MongoDB API, but simply different types of collection methods, so that we can use the app to reproduce various behaviours (and TS reporting issues).
=> NODE-2543 Added more routes for MongoDB testing

express/screener.sh, fastify/screener.sh, hapi18/screener.sh, hapi19/screener.sh, hapi20/screener.sh, koa/screener.sh, scripts/Dockerfile, scripts/Dockerfile-screener, scripts/entry.sh
This is an offshoot of https://github.com/Contrast-Security-OSS/NodeTestBenches/pull/310 which caused the pipeline to fail: https://github.com/Contrast-Security-OSS/NodeTestBenches/actions/runs/3061326288 because there is no Docker image of Node18 built for Debian "Stretch". I don't think there will be since it's no longer LTS: https://www.debian.org/releases/stretch/ but I couldn't find anything confirming or denying that. Regardless, I think it's best to get off it and use the current LTS which is "Bullseye": https://www.debian.org/releases/bullseye/
The main problem with that is mysql-client and mysql-server aren't on anything later than "Stretch": https://packages.debian.org/stretch/mysql-server (available) v. https://packages.debian.org/bullseye/mysql-server (not available) so we …
=> NODE-2635: Update Dockerfiles to be compatible with Bullseye
